task: GFP
obj_1: stability
obj_2: GFP
predictor_1_dir: logs_predictor/train_predictor_ddg4GFP_percentile_0.4_2024_01_29__00_28_59
predictor_2_dir: logs_predictor/train_predictor_GFP4ddg_2024_01_29__00_28_19
predictor_1_type: BaseCNN
predictor_2_type: BaseCNN
csv_path: data/GFP/ground_truth_GFP_stability_percentile_0.4.csv
cluster_cutoff: 500
cluster_method: null # moo or null
max_visits: 1
max_epochs: 15
# run_name: run_${now:%Y-%m-%d}_${now:%H-%M-%S} #IE_${run.max_epochs}  -- use this name if you don't want the date, but instead the number of epochs
debug: False
seed: 1
temperature: 0.01
gibbs_samples: 100
verbose: False
ckpt_name: best_checkpoints.pt
inverse_sign_1: True
inverse_sign_2: False
gradient_compose_method: pareto # average, pareto, mgda
balance_weight_1: 1
balance_weight_2: 1
weight_1: 1.0
weight_2: 1.0
lambda_method: lambda
lambd: 1.0
pref_index: 0
linear_weight_1: 0.5
linear_weight_2: 0.5
mutation_sites: null
normalize_grad: True